export const supportedCryptos = [
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin' },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum' },
  { id: 'cardano', symbol: 'ADA', name: 'Cardano' },
  { id: 'solana', symbol: 'SOL', name: 'Solana' },
  { id: 'ripple', symbol: 'XRP', name: 'XRP' },
  { id: 'polkadot', symbol: 'DOT', name: 'Polkadot' },
  { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche' },
  { id: 'chainlink', symbol: 'LINK', name: 'Chainlink' },
  { id: 'matic-network', symbol: 'MATIC', name: 'Polygon' },
  { id: 'algorand', symbol: 'ALGO', name: 'Algorand' },
  { id: 'stellar', symbol: 'XLM', name: 'Stellar' },
  { id: 'hedera-hashgraph', symbol: 'HBAR', name: 'Hedera' },
  { id: 'vechain', symbol: 'VET', name: 'VeChain' },
  { id: 'iota', symbol: 'MIOTA', name: 'IOTA' },
  { id: 'quant-network', symbol: 'QNT', name: 'Quant' },
  { id: 'xdce-crowd-sale', symbol: 'XDC', name: 'XDC Network' },
  { id: 'constellation-labs', symbol: 'DAG', name: 'Constellation' },
  { id: 'ondo-finance', symbol: 'ONDO', name: 'Ondo' },
  { id: 'casper-network', symbol: 'CSPR', name: 'Casper Network' },
  { id: 'gala', symbol: 'GALA', name: 'Gala' },
  { id: 'clearpool', symbol: 'CPOOL', name: 'Clearpool' },
  { id: 'propy', symbol: 'PRO', name: 'Propy' },
  { id: 'realy-metaverse', symbol: 'REAL', name: 'Realy' },
  { id: 'realio-network', symbol: 'RIO', name: 'Realio Network' },
  { id: 'wormhole', symbol: 'W', name: 'Wormhole' },
  { id: 'axelar', symbol: 'AXL', name: 'Axelar' },
  { id: 'zebec-protocol', symbol: 'ZBCN', name: 'Zebec Protocol' },
  { id: 'flare-networks', symbol: 'FLR', name: 'Flare' },
  { id: 'polkadex', symbol: 'PDEX', name: 'Polkadex' },
  { id: 'energy-web-token', symbol: 'EWT', name: 'Energy Web Token' },
  { id: 'exnetwork-token', symbol: 'EXFI', name: 'Exnetwork' },
  { id: 'lcx', symbol: 'LCX', name: 'LCX' },
  { id: 'pendle', symbol: 'PENDLE', name: 'Pendle' },
  { id: 'sui', symbol: 'SUI', name: 'Sui' },
  { id: 'solo-coin', symbol: 'SOLO', name: 'Solo' },
  { id: 'dogecoin', symbol: 'DOGE', name: 'Dogecoin' },
  { id: 'bone-shibaswap', symbol: 'BONE', name: 'Bone ShibaSwap' },
  { id: 'coreum', symbol: 'COREUM', name: 'Coreum' },
].sort((a, b) => a.symbol.localeCompare(b.symbol))

export const supportedStocks = [
  { symbol: 'XRPZ', name: 'XRPZ Stock' },
  { symbol: 'XRP', name: 'XRP Stock' },
  { symbol: 'XRPC', name: 'XRPC Stock' },
  { symbol: 'XRPI', name: 'XRPI Stock' },
  { symbol: 'PRXRF', name: 'PRXRF Stock' },
  { symbol: 'XRPT', name: 'XRPT Stock' },
  { symbol: 'WPM', name: 'Wheaton Precious Metals' },
  { symbol: 'XXRP', name: 'XXRP Stock' },
  { symbol: 'GLD', name: 'SPDR Gold Shares' },
  { symbol: 'IAU', name: 'iShares Gold Trust' },
  { symbol: 'PHYS', name: 'Sprott Physical Gold' },
  { symbol: 'FNV', name: 'Franco-Nevada' },
].sort((a, b) => a.symbol.localeCompare(b.symbol))
